[phases.setup]
nixPkgs = ["python311Full", "timidity", "lame"]

[phases.install]
cmds = ["python3 -m venv /opt/venv", "/opt/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "cd backend && /opt/venv/bin/python3 server.py"
