[phases.setup]
nixPkgs = ["python311Full", "timidity"]

[phases.install]
cmds = ["python3 -m ensurepip", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python3 server.py"
